-- V1: initial FraternityOS schema.
-- Enums are modeled as varchar + CHECK constraints so they map cleanly to
-- JPA @Enumerated(EnumType.STRING) and remain trivial to evolve.
--
-- Identity is split from house membership:
--   * app_user  -- a person's account; exists independently of any house.
--   * house     -- tenant root; every domain row is scoped to a house.
--   * membership -- links one user to one house (a user has at most one).
-- Domain rows reference a MEMBERSHIP (never a user directly), so a person's
-- house-specific history survives even after they go ALUMNI.
-- ("user" is a reserved word in Postgres, hence the app_user table name.)

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone         VARCHAR(30),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_app_user_email UNIQUE (email)
);

CREATE TABLE house (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(150) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE membership (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES app_user (id),
    house_id     BIGINT      NOT NULL REFERENCES house (id),
    status       VARCHAR(20) NOT NULL,
    room         VARCHAR(50),
    joined_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    graduated_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- A user belongs to at most one house.
    CONSTRAINT uq_membership_user   UNIQUE (user_id),
    CONSTRAINT ck_membership_status CHECK (status IN ('ACTIVE', 'ALUMNI'))
);
CREATE INDEX idx_membership_house ON membership (house_id);

-- Positions are global catalog entries (President, Treasurer, Kitchen Manager,
-- ...). They are assigned to memberships and, per the current authorization
-- model, President/Treasurer grant permissions.
CREATE TABLE position (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_position_name UNIQUE (name)
);

INSERT INTO position (name, description) VALUES
    ('President',            'Head of the house; full administrative permissions.'),
    ('Treasurer',            'Manages finances and rent statements.'),
    ('Kitchen Manager',      'Coordinates kitchen and meals.'),
    ('Social Director',      'Organizes social events.'),
    ('Maintenance Director', 'Oversees repairs and upkeep.');

CREATE TABLE membership_position (
    membership_id BIGINT      NOT NULL REFERENCES membership (id),
    position_id   BIGINT      NOT NULL REFERENCES position (id),
    assigned_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (membership_id, position_id)
);

CREATE TABLE announcement (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id             BIGINT       NOT NULL REFERENCES house (id),
    author_membership_id BIGINT       NOT NULL REFERENCES membership (id),
    title                VARCHAR(200) NOT NULL,
    content              TEXT         NOT NULL,
    is_pinned            BOOLEAN      NOT NULL DEFAULT false,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_announcement_house ON announcement (house_id);

CREATE TABLE event (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id                 BIGINT       NOT NULL REFERENCES house (id),
    created_by_membership_id BIGINT       NOT NULL REFERENCES membership (id),
    title                    VARCHAR(200) NOT NULL,
    description              TEXT,
    location                 VARCHAR(200),
    start_date               TIMESTAMPTZ  NOT NULL,
    end_date                 TIMESTAMPTZ,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_event_house ON event (house_id);

CREATE TABLE responsibility (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id        BIGINT       NOT NULL REFERENCES house (id),
    title           VARCHAR(200) NOT NULL,
    description     TEXT,
    type            VARCHAR(20)  NOT NULL,
    rotation_days   INTEGER,
    rotation_cursor INTEGER,
    active          BOOLEAN      NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_responsibility_type CHECK (type IN ('FIXED', 'ROTATING'))
);
CREATE INDEX idx_responsibility_house ON responsibility (house_id);

CREATE TABLE responsibility_member (
    responsibility_id BIGINT  NOT NULL REFERENCES responsibility (id),
    membership_id     BIGINT  NOT NULL REFERENCES membership (id),
    rotation_order    INTEGER NOT NULL,
    PRIMARY KEY (responsibility_id, membership_id)
);

CREATE TABLE responsibility_assignment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsibility_id BIGINT      NOT NULL REFERENCES responsibility (id),
    membership_id     BIGINT      NOT NULL REFERENCES membership (id),
    status            VARCHAR(20) NOT NULL,
    assigned_date     DATE        NOT NULL,
    due_date          DATE        NOT NULL,
    completed_at      TIMESTAMPTZ,
    CONSTRAINT ck_assignment_status CHECK (status IN ('PENDING', 'COMPLETED', 'OVERDUE'))
);
CREATE INDEX idx_assignment_responsibility ON responsibility_assignment (responsibility_id);
CREATE INDEX idx_assignment_membership     ON responsibility_assignment (membership_id);

CREATE TABLE monthly_statement (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id                 BIGINT      NOT NULL REFERENCES house (id),
    uploaded_by_membership_id BIGINT     NOT NULL REFERENCES membership (id),
    month                    INTEGER     NOT NULL,
    year                     INTEGER     NOT NULL,
    notes                    TEXT,
    attachment_url           VARCHAR(500),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_statement_period UNIQUE (house_id, year, month),
    CONSTRAINT ck_statement_month  CHECK (month BETWEEN 1 AND 12)
);
CREATE INDEX idx_statement_house ON monthly_statement (house_id);

CREATE TABLE payment (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monthly_statement_id BIGINT        NOT NULL REFERENCES monthly_statement (id),
    membership_id        BIGINT        NOT NULL REFERENCES membership (id),
    amount               NUMERIC(10,2) NOT NULL,
    status               VARCHAR(20)   NOT NULL,
    paid_at              TIMESTAMPTZ,
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_payment_membership UNIQUE (monthly_statement_id, membership_id),
    CONSTRAINT ck_payment_status     CHECK (status IN ('PENDING', 'PAID'))
);
CREATE INDEX idx_payment_statement ON payment (monthly_statement_id);
