-- V2: house join requests.
-- A user without a house may request to join an existing one. A President
-- approves later (approval flow is a separate task); until then the request
-- sits PENDING. A user may hold at most one PENDING request per house.

CREATE TABLE join_request (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id   BIGINT      NOT NULL REFERENCES house (id),
    user_id    BIGINT      NOT NULL REFERENCES app_user (id),
    status     VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_at TIMESTAMPTZ,
    CONSTRAINT ck_join_request_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);
CREATE INDEX idx_join_request_house ON join_request (house_id);
CREATE INDEX idx_join_request_user  ON join_request (user_id);

-- At most one outstanding (PENDING) request per user + house.
CREATE UNIQUE INDEX uq_join_request_pending
    ON join_request (user_id, house_id) WHERE status = 'PENDING';
